travis deploy error fixes (#180)
* travis deploy error fixes

was giving 

The command "ruby -S gem install dpl -v 2.0.5.4" failed and exited with 1 during .
Your build has been stopped.
ERROR:  Error installing dpl:
	There are no versions of dpl (= 2.0.5.4) compatible with your Ruby & RubyGems
	dpl requires Ruby version >= 3.1. The current ruby version is 2.7.1.83.

* removed dup skip_cleanup